# -*-python-*-
import os, re

Import("env")

# 1. Select and install the headers

include_dir = str(env.Dir("../include").srcnode())
h_pattern = re.compile(r".*\.(h|hpp)$")
includes = ["../include/%s" % ( s, ) for s in os.listdir(include_dir) if h_pattern.match( s )]

env.ALEAIncludes("container", includes)


# Build shared libraries

# 2. Build grid library
sources = ["id_generator.cpp",
	   "grid.cpp",
	   "relation.cpp",
	   "graph.cpp",
	   "topomesh.cpp",
	   "property_map.cpp"]
target = "container"

# Add defines to export symbols on Windows
DEFINES = list(env['CPPDEFINES'])
DEFINES.append('SCENEOBJ_DLL')

# Build the library
lib1 = env.ALEALibrary(target, sources, CPPDEFINES=DEFINES)

