# -*-python-*-

import os
from openalea.sconsx import config, environ


ALEASolution = config.ALEASolution

pj = os.path.join

SConsignFile()

options = Variables(['../options.py', 'options.py'], ARGUMENTS)
tools = ['']

env = ALEASolution(options, tools)
env.Append(LIBS=['z','m'])
#env.Append(CCFLAGS='-g')
# Set build directory

prefix = env['build_prefix']

# Build stage
prefix= env['build_prefix']
SConscript( pj(prefix,"src/c/SConscript"),
            exports={"env":env} )

#SConscript(pj(prefix,"src/wrapper/SConscript"), exports="env")

Default("build")
