# -*-python-*-

Import( "env" )

lib_env = env.Clone()
lib_env.EnableQt4Modules(['QtCore','QtOpenGL'])

includes= lib_env.ALEAGlob('*.h')
sources= lib_env.ALEAGlob('*.cpp')


pgllibs = ['pglalgo', 'pglgui', 'pglsg', 'pgltool']

lib_env.AppendUnique(LIBS=['vptool'] + pgllibs)

inc= lib_env.ALEAIncludes( "msvoxel", includes )
lib = lib_env.ALEALibrary( "vpoctree", sources)





