# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'vplants.tissue_analysis'
__version__ = '0.9.0'
__license__ = 'CeCILL-C'
__author__ = None
__institutes__ = None
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = ''
__alias__ = []

__all__ = []


extraction_vol_L1 = Factory(name='L1 Extraction',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='extraction_vol_L1',
                inputs=({'interface': IFileStr, 'name': 'Stack (Spatial Image)'}, {'interface': IStr, 'name': 'Save as', 'value': ''}, {'interface': IBool, 'name': 'Remove cells at the margins', 'value': True}),
                outputs=({'interface': None, 'name': 'Extracted spatial image'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('extraction_vol_L1')


wra_LienTissuTXT = Factory(name='LienTissuTXT',
                authors='Vincent MIRABET',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='wra_LienTissuTXT',
                inputs=({'interface': IFileStr, 'name': 'Lineage'},),
                outputs=({'interface': None, 'name': 'Lineage t1->t2 Dictionary'},{'interface': None, 'name': 'Lineage t2->t1 Dictionary'},{'interface': None, 'name': 'LineageTXT Dictionary'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('wra_LienTissuTXT')


volumetric_growth = Factory(name='Volumetric Growth',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='volumetric_growth',
                inputs=({'interface': IFileStr, 'name': 'Stack @ t_n'},{'interface': IFileStr, 'name': 'Stack @ t_n+1'},{'interface': None, 'name': 'TXT Lineage'},),
                outputs=({'interface': None, 'name': 'Volumetric Growth Dictionary (*keys= t_n cells ids)'},{'interface': None, 'name': 'Inverted Volumetric Growth Dictionary (*keys= t_n+1 cells ids)'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('volumetric_growth')


nb_Daugthers = Factory(name='Number of Daugthers',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='nb_Daugthers',
                inputs=({'interface': None, 'name': 'Lineage t1->t2'},),
                outputs=({'interface': None, 'name': 'Dict Nb Daugthers'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('nb_Daugthers')


vtk_volume = Factory(name='3D colored cells VTK',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='vtk_volume',
                inputs=({'interface': IFileStr, 'name': 'Stack (Spatial Image)'},{'interface': None, 'name': 'TXT Lineage'},{'interface': None, 'name': 'data to plot'},{'interface': IStr, 'name': 'legend title'},),
                outputs=({'interface': None, 'name': 'VTK actor'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('vtk_volume')


Global_Display = Factory(name='iVTK Display',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='Global_Display',
                inputs=({'interface': None, 'name': 'list of VTK actor'},),
                outputs=({'interface': None, 'name': '3D Display'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('Global_Display')


surface_cells_labels = Factory(name='Cells labelling',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='surface_cells_labels',
                inputs=({'interface': IFileStr, 'name': 'Stack (Spatial Image)'},{'interface': None, 'name': 'TXT Lineage'},{'interface': None, 'name': 'data to plot'},{'interface': IBool, 'name': '@ t_n+1'},),
                outputs=({'interface': None, 'name': '3D Display of data'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('surface_cells_labels')


extraction_surf_L1 = Factory(name='L1 Surface Extraction',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='extraction_surf_L1',
                inputs=({'interface': IFileStr, 'name': 'Stack (Spatial Image)'},{'interface': IBool, 'name': 'Return Surface Spatial Image'},{'interface': IBool, 'name': 'Remove margins'' cells'},),
                outputs=({'interface': None, 'name': 'x'},{'interface': None, 'name': 'y'},{'interface': None, 'name': 'z'},{'interface': None, 'name': 'L1 list'},{'interface': None, 'name': 'Surface Spatial Iamge'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('extraction_surf_L1')


lineage_extension = Factory(name='Lineage extension',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='lineage_extension',
                inputs=({'interface': None, 'name': 't_n -> t_n+1 TXT Lineage'},{'interface': None, 'name': 't_n+1 -> t_n+2 TXT Lineage'},),
                outputs=({'interface': None, 'name': 't_n -> t_n+2 Lineage'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('lineage_extension')


Strain_2D = Factory(name='Surface Strain',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='Strain_2D',
                inputs=({'interface': IFileStr, 'name': 'Stack @ t_n(Spatial Image)'},{'interface': IFileStr, 'name': 'Stack @ t_n+1(Spatial Image)'},{'interface': None, 'name': 't_n -> t_n+1 TXT Lineage'},{'interface': None, 'name': 't_n+1 -> t_n TXT Lineage'},{'interface': IInt, 'name': 'Time interval bewteen t_n & t_n+1'},),
                outputs=({'interface': None, 'name': 'Strain Rate'},{'interface': None, 'name': 'Areal Strain Rate'},{'interface': None, 'name': 'Growth Anisotropy'},{'interface': None, 'name': 't_n strain cross in 3D (tensor)'},{'interface': None, 'name': 't_n+1 strain cross in 3D (tensor)'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('Strain_2D')


vtk_cells_surf = Factory(name='Colored Cells Surface',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='vtk_cells_surf',
                inputs=({'interface': None, 'name': 'x'},{'interface': None, 'name': 'y'},{'interface': None, 'name': 'z'},{'interface': None, 'name': 'Cells List'},{'interface': None, 'name': 'Surface Stack'},),
                outputs=({'interface': None, 'name': 'vtk actor of cells surface'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('vtk_cells_surf')


vtk_cells_ids = Factory(name='Ids Cells Surface',
                authors='Jonathan LEGRAND',
                category='vtissue',
                nodemodule='tissue_analysis_wra',
                nodeclass='vtk_cells_ids',
                inputs=({'interface': None, 'name': 'Cells List'},{'interface': None, 'name': 'Surface Stack'},),
                outputs=({'interface': None, 'name': 'vtk actor of cells ids'},),
                widgetmodule=None,
                widgetclass=None,
               )

__all__.append('vtk_cells_ids')


print "__wraela__.py loaded"

