/*************************************************************************
 * reech-def.h -
 *
 * $Id: reech-def.begin,v 1.2 2000/10/18 08:45:56 greg Exp $
 *
 * Copyright©INRIA 1999
 *
 * AUTHOR:
 * Gregoire Malandain (greg@sophia.inria.fr)
 * 
 * CREATION DATE: 
 *
 *
 * ADDITIONS, CHANGES
 *	
 *	
 *	
 *
 */


/* CAUTION
   DO NOT EDIT THIS FILE,
   UNLESS YOU HAVE A VERY GOOD REASON 
 */

#ifndef _reech_def_h_
#define _reech_def_h_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <typedefs.h>







extern void ReechTriLinDefBack_u8 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       r32* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );
extern void ReechNearestDefBack_u8 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       void* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );







extern void ReechTriLinDefBack_s8 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       r32* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );
extern void ReechNearestDefBack_s8 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       void* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );







extern void ReechTriLinDefBack_u16 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       r32* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );
extern void ReechNearestDefBack_u16 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       void* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );







extern void ReechTriLinDefBack_s16 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       r32* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );
extern void ReechNearestDefBack_s16 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       void* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );







extern void ReechTriLinDefBack_r32 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       r32* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );
extern void ReechNearestDefBack_r32 ( void *theBuf, /* buffer to be resampled */
			       int *theDim, /* dimensions of buffers */
			       void* resBuf,  /* result buffer */
			       int *resDim,  /* dimensions of this buffer */
			       r32** theDef, /* deformations */
                               int *defDim, /* dimensions of these buffers */
			       double* mat_aft,  /* transformation matrix */
			       double* mat_bef,  /* transformation matrix */
			       int slice     /* slice index */
			       );







#ifdef __cplusplus
}
#endif

#endif
