
# This file has been generated at Thu Mar  5 10:06:09 2009

from openalea.core import *


__name__ = 'demo.tissue.simu'

__editable__ = True
__description__ = 'Tissue demo simulation.'
__license__ = 'Cecill-C'
__url__ = 'http://openalea.gforge.inria.fr'
__alias__ = []
__version__ = '0.0.2'
__authors__ = 'Jerome Chopard'
__institutes__ = 'INRIA/CIRAD'
__icon__ = ''


__all__ = ['mecagrowth']



mecagrowth = CompositeNodeFactory(name='mecagrowth',
                             description='',
                             category='modelling',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('demo.tissue.growth', 'create.param'),
   3: ('demo.tissue.growth', 'init.division'),
   4: ('demo.tissue.growth', 'init.growth'),
   5: ('demo.tissue.growth', 'create.gui'),
   6: ('demo.tissue.growth', 'init.mechanics'),
   7: ('demo.tissue.growth', 'init.physiology'),
   8: ('demo.tissue.growth', 'read.tissue'),
   9: ('demo.tissue.growth', 'growth1'),
   10: ('demo.tissue.growth', 'division'),
   11: ('demo.tissue.growth', 'mechanics'),
   12: ('demo.tissue.growth', 'physiology'),
   13: ('demo.tissue.growth', 'create.simulation'),
   14: ('demo.tissue.growth', 'launch.gui'),
   15: ('demo.tissue.growth', 'redraw'),
   16: ('demo.tissue.growth', 'init.simulation'),
   17: ('demo.tissue.growth', 'cell_state1'),
   18: ('demo.tissue.growth', 'init.cell_state')},
                             elt_connections={  7746248: (18, 0, 8, 1),
   7746272: (17, 0, 13, 2),
   7746296: (8, 0, 17, 0),
   7746320: (11, 0, 13, 2),
   7746344: (8, 0, 10, 0),
   7746368: (10, 0, 13, 2),
   7746392: (8, 0, 14, 3),
   7746416: (9, 0, 13, 2),
   7746440: (8, 0, 12, 0),
   7746464: (15, 0, 13, 2),
   7746488: (5, 0, 16, 0),
   7746512: (2, 0, 7, 0),
   7746536: (8, 0, 5, 0),
   7746560: (5, 0, 14, 0),
   7746584: (13, 0, 14, 2),
   7746608: (3, 0, 18, 0),
   7746632: (16, 0, 13, 1),
   7746656: (8, 0, 9, 0),
   7746680: (8, 0, 11, 0),
   7746704: (7, 0, 6, 0),
   7746728: (5, 1, 14, 1),
   7746752: (12, 0, 13, 2),
   7746776: (8, 0, 13, 0),
   7746800: (5, 0, 15, 0),
   7746824: (4, 0, 3, 0),
   7746848: (6, 0, 4, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'create.param',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 87.5,
         'posy': 32.5,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'init.division',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 496.25,
         'posy': 78.75,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'init.growth',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 396.25,
         'posy': 78.75,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'create.gui',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 897.5,
         'posy': 271.25,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'init.mechanics',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 272.5,
         'posy': 78.75,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'init.physiology',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 148.75,
         'posy': 78.75,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'read.tissue',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 328.75,
         'posy': 147.5,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'growth1',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 435.0,
         'posy': 347.5,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'division',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 28.75,
          'posy': 346.25,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'mechanics',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 327.5,
          'posy': 347.5,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'physiology',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 118.75,
          'posy': 346.25,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'create.simulation',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 711.25,
          'posy': 505.0,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': 'launch.gui',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 868.75,
          'posy': 697.5,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': 'redraw',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 832.5,
          'posy': 350.0,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'init.simulation',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 698.75,
          'posy': 350.0,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': 'cell_state1',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 226.25,
          'posy': 346.25,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'init.cell_state',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 607.5,
          'posy': 80.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [],
   3: [],
   4: [],
   5: [],
   6: [],
   7: [],
   8: [(0, "'/home/chopard/dvlpt/vplants/demo/tissue_growth/tissue.zip'")],
   9: [],
   10: [],
   11: [],
   12: [],
   13: [],
   14: [],
   15: [],
   16: [],
   17: [],
   18: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




