# -*-python-*-

import os
from openalea.sconsx import config, environ

ALEASolution = config.ALEASolution
pj = os.path.join

name = 'pglviewer'

options = Options('options.py', ARGUMENTS)
tools = ['boost_python', 'alea']

env = ALEASolution(options, tools)

prefix = env['build_prefix']
# Build stage
#SConscript(pj(prefix,"src/cpp/SConscript"), exports={"env": cpp_env})
#SConscript(pj(prefix,"src/wrapper/SConscript"), exports={"env":wrapper_env})

Default("build")
