# -*-python-*-

import os
bn = os.path.basename

Import( "env" )

lib_env = env.Clone()

# Import/Export symbols for windows
if lib_env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    lib_env.AppendUnique(LINKFLAGS=LINKFLAGS)

includes= lib_env.ALEAGlob('*.h')
sources = lib_env.ALEAGlob('*.c')

# Add defines to export symbols on Windows
#lib_env.AppendUnique(CPPDEFINES=['MESSAGE'])
#lib_env.AppendUnique(LIBS=[''])

inc = lib_env.ALEAIncludes( 'io', includes )
inc1 = lib_env.ALEAIncludes( 'io/imageio', lib_env.ALEAGlob('*.h','imageio') )
lib = lib_env.ALEALibrary( 'io', sources )
