
# This file has been generated at Wed Aug 17 11:34:19 2011

from openalea.core import *


__name__ = 'vplants.mars_alt.demo.alt'

__editable__ = True
__description__ = 'mars_alt nodes'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr/doc/openalea/pylab/doc/_build/html/contents.html'
__alias__ = []
__version__ = '0.8.0'
__authors__ = 'Eric Moscardi'
__institutes__ = 'INRIA/CIRAD'
__icon__ = 'logo.png'


__all__ = ['mapping', '_200178572']



mapping = CompositeNodeFactory(name='mapping',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  3: ('openalea.image.serial', 'imread'),
   4: ('openalea.image.serial', 'imread'),
   5: ('vplants.mars_alt.nodes.lineaging.mapping', 'candidates'),
   6: ('vplants.mars_alt.nodes.lineaging.mapping', 'candidates'),
   9: ('vplants.mars_alt.nodes.lineaging.io', 'read_lineage'),
   10: ('vplants.mars_alt.nodes.lineaging.mapping', 'full_mapping'),
   11: ('vplants.mars_alt.nodes.lineaging.io', 'read_lineage'),
   12: ('openalea.image.serial', 'imread'),
   14: ('openalea.flow control', 'annotation'),
   15: ('openalea.image.serial', 'imread'),
   16: ('openalea.numpy.math', 'max'),
   17: ('openalea.numpy.math', 'max'),
   18: ('vplants.mars_alt.nodes.lineaging.mapping', 'optimal_lineage'),
   19: ('vplants.mars_alt.nodes.lineaging.mapping', 'optimal_lineage'),
   20: ('openalea.flow control', 'annotation')},
                             elt_connections={  154218396: (11, 0, 19, 3),
   154218408: (11, 0, 18, 3),
   154218420: (5, 0, 19, 2),
   154218432: (6, 0, 18, 2),
   154218444: (16, 0, 19, 1),
   154218456: (9, 0, 10, 3),
   154218468: (12, 0, 10, 1),
   154218480: (15, 0, 10, 0),
   154218504: (3, 0, 5, 0),
   154218528: (4, 0, 5, 1),
   154218540: (17, 0, 19, 0),
   154218552: (4, 0, 6, 1),
   154218564: (16, 0, 18, 1),
   154218576: (4, 0, 16, 0),
   154218588: (3, 0, 17, 0),
   154218612: (17, 0, 18, 0),
   154218648: (3, 0, 6, 0)},
                             elt_data={  3: {  'block': False,
         'caption': 'imread',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb0f6e8c> : "imread"',
         'hide': True,
         'id': 3,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -818.1568136833537,
         'posy': -255.6044435795078,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'imread',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb0f6e8c> : "imread"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -544.8946594897665,
         'posy': -255.6044435795078,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'candidates',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xf1a8fec> : "candidates"',
         'hide': True,
         'id': 5,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -581.8946594897665,
         'posy': -88.5,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'candidates',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xf1a8fec> : "candidates"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -855.1568136833537,
         'posy': -88.5,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'read_lineage',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xf1a8dcc> : "read_lineage"',
         'hide': True,
         'id': 9,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -1137.0,
         'posy': -139.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'full_mapping',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xae82d0c> : "full_mapping"',
          'hide': True,
          'id': 10,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -1187.0,
          'posy': 53.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   11: {  'block': False,
          'caption': 'read_lineage',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xf1a8dcc> : "read_lineage"',
          'hide': True,
          'id': 11,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -701.0,
          'posy': 91.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   12: {  'block': False,
          'caption': 'imread',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb0f6e8c> : "imread"',
          'hide': True,
          'id': 12,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -1209.1839784692993,
          'posy': -136.6044435795078,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   14: {  'factory': '<openalea.core.node.NodeFactory object at 0xae7890c> : "annotation"',
          'id': 14,
          'posx': -1335.0,
          'posy': -196.0,
          'txt': u'This is the compact version of the dataflow needed to compute lineages\nfrom the segmented images.'},
   15: {  'block': False,
          'caption': 'imread',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xb0f6e8c> : "imread"',
          'hide': True,
          'id': 15,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -1277.9704410500608,
          'posy': -136.6044435795078,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   16: {  'block': False,
          'caption': 'max',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xa983e0c> : "max"',
          'hide': True,
          'id': 16,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -659.1483193776892,
          'posy': -30.378155588071436,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   17: {  'block': False,
          'caption': 'max',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xa983e0c> : "max"',
          'hide': True,
          'id': 17,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -719.3751702574032,
          'posy': -30.378155588071436,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   18: {  'block': False,
          'caption': 'nx_flow',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xf1a8f6c> : "optimal_lineage"',
          'hide': True,
          'id': 18,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -854.6568136833537,
          'posy': 138.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   19: {  'block': False,
          'caption': 'rf_flow',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xf1a8f6c> : "optimal_lineage"',
          'hide': True,
          'id': 19,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -581.3946594897665,
          'posy': 138.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   20: {  'factory': '<openalea.core.node.NodeFactory object at 0xae7890c> : "annotation"',
          'id': 20,
          'posx': -908.0,
          'posy': -309.0,
          'txt': u'These two different (although connected) dataflows do the same task as the one on the left.\nThis shows that the subfunctions are also available for you to play with.'},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  3: [  (  0,
            "'/user/dbarbeau/home/Devel/hackaton/Daniel-mapping/imgSegDefStep2_1_12_iter_1_TEST_INIT_12.inr.gz'")],
   4: [  (  0,
            "'/user/dbarbeau/home/Devel/hackaton/Daniel-mapping/imgSeg_2_12.inr.gz'")],
   5: [(2, '3'), (3, '8'), (4, '1'), (5, 'True'), (6, "'cell_shape'")],
   6: [(2, '3'), (3, '8'), (4, '1'), (5, 'True'), (6, "'cell_shape'")],
   9: [(0, 'None')],
   10: [  (2, '3'),
          (4, '8'),
          (5, 'False'),
          (6, "'cell_shape'"),
          (7, "'rf_flow'")],
   11: [(0, 'None')],
   12: [  (  0,
             "'/user/dbarbeau/home/Devel/hackaton/Daniel-mapping/imgSeg_2_12.inr.gz'")],
   14: [],
   15: [  (  0,
             "'/user/dbarbeau/home/Devel/hackaton/Daniel-mapping/imgSegDefStep2_1_12_iter_1_TEST_INIT_12.inr.gz'")],
   16: [(1, 'None')],
   17: [(1, 'None')],
   18: [(4, '8'), (5, "'nx_simplex'")],
   19: [(4, '8'), (5, "'rf_flow'")],
   20: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-130.20807473307616, -70.35858587489358],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [-818.1568136833537, -255.6044435795078],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [-544.8946594897665, -255.6044435795078],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-581.8946594897665, -88.5],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [-855.1568136833537, -88.5],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [-368.8851725920915, 49.72816691296703],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [-142.037756217514, 53.61404803022519],
         'useUserColor': False,
         'userColor': None},
   9: {  'position': [-1137.0, -139.0],
         'useUserColor': False,
         'userColor': None},
   10: {  'position': [-1187.0, 53.0], 'useUserColor': False, 'userColor': None},
   11: {  'position': [-701.0, 91.0], 'useUserColor': False, 'userColor': None},
   12: {  'position': [-1209.1839784692993, -136.6044435795078],
          'useUserColor': False,
          'userColor': None},
   13: {  'position': [-310.91371923717577, 144.59659996459476],
          'useUserColor': False,
          'userColor': None},
   14: {  'color': None,
          'position': [-1335.0, -196.0],
          'rectP2': (387.0, 315.5),
          'text': u'This is the compact version of the dataflow needed to compute lineages\nfrom the segmented images.',
          'textColor': None,
          'visualStyle': 1},
   15: {  'position': [-1277.9704410500608, -136.6044435795078],
          'useUserColor': False,
          'userColor': None},
   16: {  'position': [-659.1483193776892, -30.378155588071436],
          'useUserColor': False,
          'userColor': None},
   17: {  'position': [-719.3751702574032, -30.378155588071436],
          'useUserColor': False,
          'userColor': None},
   18: {  'position': [-854.6568136833537, 138.0],
          'useUserColor': False,
          'userColor': None},
   19: {  'position': [-581.3946594897665, 138.0],
          'useUserColor': False,
          'userColor': None},
   20: {  'color': None,
          'position': [-908.0, -309.0],
          'rectP2': (493.0, 492.5),
          'text': u'These two different (although connected) dataflows do the same task as the one on the left.\nThis shows that the subfunctions are also available for you to play with.',
          'textColor': None,
          'visualStyle': 1},
   '__in__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_200178572 = CompositeNodeFactory(name='deformation_field',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.image.serial', 'imread'),
   4: ('vplants.mars_alt.nodes.lineaging.io', 'read_lineage'),
   6: ('openalea.image.serial', 'imsave'),
   7: ('openalea.image.serial', 'imread'),
   8: ('vplants.mars_alt.nodes.registration', 'lineage2deformation')},
                             elt_connections={  161669404: (8, 0, 6, 1),
   161669428: (7, 0, 8, 0),
   161669440: (2, 0, 8, 1),
   161669452: (4, 0, 8, 2)},
                             elt_data={  2: {  'block': False,
         'caption': 'imread',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xba8248c> : "imread"',
         'hide': True,
         'id': 2,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -136.38742613029547,
         'posy': -161.36842292630828,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'read_lineage',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb80ea2c> : "read_lineage"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -37.64316126735493,
         'posy': -161.36842292630828,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'imsave',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xba823ec> : "imsave"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -122.85551260436466,
         'posy': -9.168321836146614,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'imread',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xba8248c> : "imread"',
         'hide': True,
         'id': 7,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -261.56310430758276,
         'posy': -161.36842292630828,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'lineage2deformation',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xba5e22c> : "lineage2deformation"',
         'hide': True,
         'id': 8,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -164.72955500178,
         'posy': -68.42348166607334,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (  0,
            "'/user/dbarbeau/home/Devel/hackaton/Daniel-mapping/imgSeg_2_12.inr.gz'")],
   4: [  (  0,
            "'/user/dbarbeau/home/Devel/hackaton/Daniel-mapping/mapping_init_TEST_INIT_12_iter_1_TEST_INIT_12'")],
   6: [(0, "'/user/dbarbeau/home/tests/my_landmarks/alt_defo.inr.gz'")],
   7: [  (  0,
            "'/user/dbarbeau/home/Devel/hackaton/Daniel-mapping/imgSegDefStep2_1_12_iter_1_TEST_INIT_12.inr.gz'")],
   8: [(3, '0.5')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-136.38742613029547, -161.36842292630828], 'userColor': None, 'useUserColor': False},
   3: {  'position': [-172.0, -168.5], 'useUserColor': False, 'userColor': None},
   4: {'position': [-37.64316126735493, -161.36842292630828], 'userColor': None, 'useUserColor': False},
   5: {  'position': [-198.33795013850414, -87.53462603878117],
         'useUserColor': False,
         'userColor': None},
   6: {'position': [-122.85551260436466, -9.168321836146614], 'userColor': None, 'useUserColor': False},
   7: {'position': [-261.56310430758276, -161.36842292630828], 'userColor': None, 'useUserColor': False},
   8: {'position': [-164.72955500178, -68.42348166607334], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




