# -*-python-*-
Import( "env" )
import os
pj = os.path.join

# 1. Select and install the headers

#includes= env.ALEAGlob('*.h')



# 2. Call other SConscript files in sub directories
#dirs= env.ALEAGlob( 'SConscript' , dir='*')
subdirs = ['libio','libbasic','libvt', 'baladin', 'lineaging']
dirs = ['io','basic','vt', 'baladin', 'mapping']
for d in dirs:
    env.Prepend( CPPPATH = pj( '$build_includedir', d ) )

subdirs = [ pj(i,'SConscript') for i in subdirs]

SConscript( subdirs, exports= { 'env' : env } )
