# -*-python-*-

Import("env")

py_dir = '../cmechanics'

# Build wrappers as shared libraries
# First wrapper
env1 = env.Clone()

sources = ["cmechanics_wrap.cpp",
           "export_spring.cpp",
           "export_spring_fem.cpp",
           "export_mass_spring_solver.cpp",
           ]
target = "_cmechanics"
lib1 = ["cmechanics"]

env1.AppendUnique(LIBS=lib1)
env1.ALEAWrapper(py_dir, target, sources)



